### ISSUE TITLE
Design Review: Operator Fee

### ISSUE THREAD

**Issue by yuwen01** [ethereum-optimism/design-docs#110]
**Title of Meeting**

**Date, Time and Duration**

Friday, Oct 4 2024, 11:30am - 12pm PDT

**Link to design doc**

Design doc: [https://github.com/ethereum-optimism/design-docs/pull/81](https://github.com/ethereum-optimism/design-docs/pull/81)

**Additional Context**

Spec: [https://github.com/ethereum-optimism/specs/pull/382](https://github.com/ethereum-optimism/specs/pull/382)

**Comment by op-aaron** [comment]
@yuwen01 - I apologize as I was out of the office yesterday when this was posted and was not able to post before the start of the meeting.  Would it be possible to reschedule this?  Please let me know the new date and I can get up promptly!

**Comment by op-aaron** [comment]
@yuwen01 - I apologize as I was out of the office yesterday when this was posted but I see that you got it booked🙏. I'm going to close considering it resolved but please let me know if you have any questions or need anything else!
