### ISSUE TITLE
Design Review: Proofs Incident Response Improvements #2

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/design-docs#120]
**Title of Meeting**
Design Review: Proofs Incident Response Improvements 2

**Date, Time and Duration**
Design Review: Proofs Incident Response Improvements 2
Tuesday, October 15 · 4:00 – 5:00pm
Time zone: America/New_York
Google Meet joining info
Video call link: https://meet.google.com/byd-kcww-var
Or dial: ‪(US) +1 321-420-4234‬ PIN: ‪786 935 878‬#
More phone numbers: https://tel.meet/byd-kcww-var?pin=3037175856157

**Link to design doc**
We will be reviewing 5 design docs:
- https://github.com/ethereum-optimism/design-docs/pull/85
- https://github.com/ethereum-optimism/design-docs/pull/80
- https://github.com/ethereum-optimism/design-docs/pull/77
- https://github.com/ethereum-optimism/design-docs/pull/76
- https://github.com/ethereum-optimism/design-docs/pull/89

**Additional Context**
Please note that this will be the FINAL design review before these designs are either accepted or rejected. Please participate!

**Comment by op-aaron** [comment]
Looks like this was added so closing but let me know if you need any assistance @smartcontracts
