### ISSUE TITLE
request to schedule: Holocene FMA Review session

### ISSUE THREAD

**Issue by geoknee** [ethereum-optimism/design-docs#128]
**Title of Meeting**
Holocene FMA Review

**Date, Time and Duration**
10th October 2024
1600-1630 UTC

**Link to design doc**
https://github.com/ethereum-optimism/design-docs/pull/127

**Additional Context**
**Requested Attendees**

@sebastianst @Inphi @roberto-bayardo @geoknee @maurelian @benjaminion @tynes

**Comment by op-aaron** [comment]
@geoknee - This event has been created so I will close the ticket but please let me know if you see any issues with the invite or have any questions.  Thank you!
