### ISSUE TITLE
Design Review: Standard L2 Genesis:

### ISSUE THREAD

**Issue by maurelian** [ethereum-optimism/design-docs#137]
**Title of Meeting**

Standard L2 Genesis: https://github.com/ethereum-optimism/design-docs/pull/97

**Date, Time and Duration**

Monday, October 21⋅2:30 – 3:00pm

Design Review: Standard L2 Genesis - PR #97
Monday, October 21 · 2:30 – 3:00pm
Time zone: America/Toronto
Google Meet joining info
Video call link: https://meet.google.com/tia-oiur-guv
Or dial: ‪(CA) +1 437-781-4585‬ PIN: ‪786 671 363 6343‬#
More phone numbers: https://tel.meet/tia-oiur-guv?pin=7866713636343

**Requested Attendees**

@mds1 

Optional:
- @smartcontracts 
- @tynes 
- @mslipper

**Comment by op-aaron** [comment]
@maurelian - I just posted this on the public cal and with the details above.  The only difference is that I used the auto-generated google meet link as I had trouble replacing it with what you posted.  Let me know if that is a problem or if you see any issues.

**Comment by maurelian** [comment]
> @maurelian - I just posted this on the public cal and with the details above.  The only difference is that I used the auto-generated google meet link as I had trouble replacing it with what you posted.  Let me know if that is a problem or if you see any issues.

All good, I updated the link above with the one from your event.
