### ISSUE TITLE
Public OP Stack Calendar Process

### ISSUE THREAD

**Issue by tynes** [ethereum-optimism/design-docs#91]
This ticket can be closed when there is an open, transparent process for adding events to the OP Stack Protocol calendar and it is documented in the readme.

The purpose of this repo is to drive alignment on engineering decisions in an open way so that it is possible to contribute to the OP Stack from any organization. The general flow of this repo is as follows:

- open a PR
- directly communicate with stakeholders asking for review
- schedule a design review meeting using a ticket
- place a design review meeting on the public calendar
- record the design review meeting, drive towards immediate next steps
- merge the pull request if aligned, otherwise improve it and have another design review meeting if necessary
- upload design review meeting recording to YouTube or another public place
- ship it

We need somebody with admin access on the public OP Stack calendar to be able to manage the calendar. It is expected that the person that proposed the meeting runs the meeting and does the recording.

**Comment by op-aaron** [comment]
As someone w/admin access, I'm happy to take point on adding events.  I would propose the following process:

Once ready to schedule the review (after reaching out to stakeholders), an issue is created & owned to me with the following information:

1. Title of meeting
2. Date & Time for meeting
3. Email addresses to invite
4. [optional] Text for the body of the invitation

Once the meeting is reflected on the calendar I would confirm with a comment and close the issue.

**Comment by tynes** [comment]
Thank you @op-aaron! I created a template for you to streamline this process in https://github.com/ethereum-optimism/.github/pull/26. Now when a person creates an issue, they will have the ability to schedule a design review meeting. I didn't make it auto tag you, that is something that I could add if you would like. Let me know if you have any feedback on this process

**Comment by tynes** [comment]
We can close this issue when the readme of this repo is updated with this information

**Comment by op-aaron** [comment]
Thanks @tynes could you please:
- Add a "duration" field to the template to capture meeting length ... unless you advise that we should timebox it with a standard time.
- Have it auto tag me - Let's start there since I'm the only one (other than you) who can add the events.

I'd say once that is done feel free to push it and we can begin trying it out!
